backtraces_path = "~/.cache/neovide/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
neovim-bin = "/usr/local/bin/nvim"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = false
vsync = true
wsl = false

[font]
normal = ["FiraCode Nerd Font Mono"] # Will use the bundled Fira Code Nerd Font by default
size = 19
hinting = "full"
edging = "antialias"

[font.features]
"FiraCode Nerd Font Mono" = [ "+ss01", "+ss07", "+ss11", "-calt", "+ss09", "+ss02", "+ss14" ]

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [1, 2]  # Thin and thick values respectively, for all sizes
